kind: pipeline
type: docker
name: pool-api

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: plugins/docker
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    settings:
      repo: registry.rpanic.com/rpanic/tyr-core
      registry: registry.rpanic.com
      tags: latest
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      dockerfile: Dockerfile

image_pull_secrets:
  - repo_login

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - master